// Code generated by ffjson <https://github.com/pquerna/ffjson>. DO NOT EDIT.
// source: credentials.go

package model

import (
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

// MarshalJSON marshal bytes to json - template
func (j *Credentials) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if j == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := j.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// MarshalJSONBuf marshal buff to json - template
func (j *Credentials) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if j == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{"username":`)
	fflib.WriteJsonString(buf, string(j.Username))
	buf.WriteString(`,"password":`)
	fflib.WriteJsonString(buf, string(j.Password))
	buf.WriteByte('}')
	return nil
}
